# Generated by Django 5.1.1 on 2024-09-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('etat', models.CharField(choices=[('Disponible', 'Disponible'), ('Appel en cour', 'Appel en cour'), ('Hors service', 'Hors service')], max_length=20)),
                ('appels_par_jour', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
