# Generated by Django 5.1.1 on 2024-09-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_appel_alter_agent_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='numero_telephone',
            field=models.CharField(default=7, max_length=15),
            preserve_default=False,
        ),
    ]
