# Generated by Django 5.1.1 on 2024-09-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_appel_numero_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(max_length=19)),
                ('id_transaction', models.CharField(max_length=50, unique=True)),
                ('date_transaction', models.DateField()),
                ('heure_transaction', models.TimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(max_length=20)),
                ('type_transaction', models.CharField(max_length=30)),
                ('code_statut', models.CharField(max_length=10)),
                ('explication', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
