# Generated by Django 5.1.1 on 2024-09-20 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=512)),
                ('is_frequently_asked', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.CharField(max_length=1024)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.frequentlyaskedquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_text', models.CharField(max_length=1024)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.question')),
            ],
        ),
    ]
